import { ArrowDown, ArrowRight, Brain, GraduationCap, Mail, Search, UserCheck } from "lucide-react";
import { Mermaid } from "@/components/mermaid";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata = { title: "How it works · QuoteDesk" };

const PIPELINE = `flowchart LR
  A[Email received] --> B[Guard<br/>length + injection check]
  B --> C[Extract<br/>fine-tuned Gemma 270M]
  C --> D{Valid JSON?}
  D -- no --> R[Repair<br/>one retry] --> D2{Valid?}
  D -- yes --> E{Confident?<br/>token log-prob x completeness}
  D2 -- yes --> E
  D2 -- no --> T
  E -- no --> T[Escalate<br/>Gemini 3.8 Flash]
  E -- yes --> F[Resolve with tools<br/>catalog, compatibility,<br/>history, stock, pricing]
  T --> F
  F --> G[Draft quote]
  G --> H[Human review]
  H -- approve / edit / reject --> I[Sent<br/>simulated]
  H -- admin corrections --> J[(Training set)]
  J --> K[Retrain on Kaggle GPU]
  K --> L{Safety gate<br/>sealed exam}
  L -- better --> C
  L -- worse --> M[Rejected, reason stored]`;

const DATA = `flowchart LR
  S[Scenario sampled in code<br/>= the ground-truth label] --> W[Gemini writes a messy email<br/>that expresses it]
  W --> V1[Code checks<br/>verbatim spans, SKUs, quantities]
  V1 --> V2[A different Gemini model<br/>extracts independently]
  V2 --> K{Agrees with the label?}
  K -- yes --> TR[train / val / exam splits]
  K -- no --> X[Dropped and logged]`;

const FAQ = [
  [
    "Why a small model?",
    "Most quote emails are routine. A 270M-parameter model fine-tuned on this one task runs on a cheap CPU, costs a fraction of a cent per email and keeps customer data in-house. The large model is kept for the hard cases, chosen by a confidence router whose threshold was measured, not guessed.",
  ],
  [
    "Where do the prices come from?",
    "Only from a deterministic pricing tool (customer tier + volume breaks). No model ever writes a price, so an email saying \"give me 50% off\" cannot change the quote. Such emails are flagged instead.",
  ],
  [
    "Why human approval?",
    "A wrong quote costs real money and trust. Every draft waits for a person. The system does the tedious 90%, flags what it is unsure about, and the human decides.",
  ],
  [
    "How does it improve itself?",
    "When an admin fixes a line where the model misread the email, that becomes a training example. After enough corrections, a new version is trained and must beat the live model on a sealed exam it has never seen. If it is worse on any key metric, it is rejected and the reason is stored.",
  ],
  [
    "Is the data real?",
    "No. The company, customers, products, equipment and emails are all synthetic. The training labels are generated by code from sampled scenarios; the large model only writes the email text, and every email is verified before use.",
  ],
];

export default function HowItWorks() {
  return (
    <div className="mx-auto max-w-6xl space-y-10 px-4 py-10">
      <section>
        <h1 className="text-3xl font-semibold tracking-tight">How it works</h1>
        <p className="mt-2 max-w-3xl text-muted-foreground">
          Three roles, like a small sales desk: a junior clerk does most of the reading, a senior expert handles what the clerk is
          unsure about, and a manager signs off on every quote.
        </p>
        <div className="mt-6 grid items-stretch gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr]">
          {[
            { icon: Mail, t: "Customer email", d: "Typos, shorthand, \"same as last time\", missing quantities." },
            { icon: Brain, t: "Junior clerk", d: "Small fine-tuned model reads it and lists what the customer wants." },
            { icon: GraduationCap, t: "Senior expert", d: "Only if the clerk is unsure: a large model double-checks." },
            { icon: UserCheck, t: "Manager", d: "Reviews the draft (parts, stock, prices from tools) and approves." },
          ].flatMap((s, i, arr) => {
            const card = (
              <Card key={s.t} className="gap-2 py-4">
                <CardHeader className="px-4">
                  <s.icon className="size-5 text-primary" />
                  <CardTitle className="text-sm">{s.t}</CardTitle>
                </CardHeader>
                <CardContent className="px-4 text-sm text-muted-foreground">{s.d}</CardContent>
              </Card>
            );
            return i < arr.length - 1
              ? [
                  card,
                  <div key={`a${i}`} className="grid place-items-center text-muted-foreground">
                    <ArrowRight className="hidden size-5 md:block" />
                    <ArrowDown className="size-5 md:hidden" />
                  </div>,
                ]
              : [card];
          })}
        </div>
        <p className="mt-3 flex items-center gap-2 text-sm text-muted-foreground">
          <Search className="size-4" /> Parts, compatibility, order history, stock and prices come from deterministic tools, never from a model.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold">The pipeline (technical)</h2>
        <p className="mb-4 text-sm text-muted-foreground">Every box is a traced step. Open any quote&apos;s trace to see inputs, outputs, timings and costs.</p>
        <Card>
          <CardContent>
            <Mermaid chart={PIPELINE} />
          </CardContent>
        </Card>
      </section>

      <section>
        <h2 className="text-xl font-semibold">How the training data was made</h2>
        <p className="mb-4 text-sm text-muted-foreground">Ground truth first: labels are correct by construction, not trusted from a model.</p>
        <Card>
          <CardContent>
            <Mermaid chart={DATA} />
          </CardContent>
        </Card>
      </section>

      <section>
        <h2 className="mb-4 text-xl font-semibold">FAQ</h2>
        <div className="grid gap-3 md:grid-cols-2">
          {FAQ.map(([q, a]) => (
            <Card key={q} className="gap-2 py-4">
              <CardHeader className="px-4">
                <CardTitle className="text-sm">{q}</CardTitle>
              </CardHeader>
              <CardContent className="px-4 text-sm text-muted-foreground">{a}</CardContent>
            </Card>
          ))}
        </div>
      </section>
    </div>
  );
}
